import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DashboardWrapper from "./dashboardWrapper";
import RegisterServiceWorkers from "./service-workers/RegisterServiceWorkers"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>GearTrace - Inventory Manager</title>
        <link rel="manifest" href="/manifest.webmanifest" />
      </head>
      <body className={inter.className}>
        <DashboardWrapper> 
        {children}
       
        </DashboardWrapper>
        <RegisterServiceWorkers/>
        </body>
    </html>
  );
}
